services:
  arisoutre:
    build: .
    container_name: bot_discord-arisoutre
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./cache:/app/cache
      - ./endpoint_alias.yaml:/app/endpoint_alias.yaml
    ports:
      - "9501:3000"
    extra_hosts:
      - "pocketbase.antredesloutres.fr:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - pocketbase_network

networks:
  pocketbase_network:
    external: true